### ISSUE TITLE
the alignment Issue with chimple character after game Completion.

### ISSUE THREAD

**Issue by Kiranks05** [chimple/chimple#77] opened 2020-09-03 05:23 UTC
![Screenshot_2020-09-02-12-01-22-803_org chimple bahama](https://user-images.githubusercontent.com/57090054/92074419-a9bf7280-edd3-11ea-8245-ba78605ff290.jpg)

**Comment by talapadi** [comment] 2020-09-11 08:58
Duplicate of #127

**Closed by talapadi** 2020-09-11 08:58 UTC
Labels: bug
