### ISSUE TITLE
welcome to chimple page many profiles

### ISSUE THREAD

**Issue by SWETHAKRISHNA2** [chimple/chimple#1850] opened 2024-01-04 10:34 UTC
. when I installed the  Master apk ,after I login through my phone number 
. I got the otp , after that I went through a how do you join as a parent or teacher.
. Then I select as a parent  and it is open welcome to Chimple page . 
. In that page many child profile are came, 
. These profile I created as a Malta excel sheet , Now this profile are showing in Chimple.

![Screenshot_20240104_154910_Chimple](https://github.com/chimple/chimple/assets/138753773/52531fc2-d511-45ba-af57-d31209a072b2)

**Comment by divyahariharan2103** [comment] 2024-01-05 06:20
Closing the task as it is not a bug, its data issue

**Closed by divyahariharan2103** 2024-01-05 06:20 UTC
